app:
  id: OpenIntegrations
  format: EDT
  base-path: "R:\\Repos\\OpenIntegrations\\src\\ru\\BSL"

  source-set:
    - path: "TestIB"
      name: TestIB
      type: "CONFIGURATION"
      purpose: ["MAIN"]
    - path: "Tests"
      name: Tests
      type: "EXTENSION"
      purpose: ["TESTS"]
    - path: "OpenIntegrations"
      name: OPI
      type: "EXTENSION"
      purpose: ["MAIN"]

  connection:
    connection-string: "Srvr='DEVSRV';Ref='OpenIntegrations';"

  tools:
    builder: DESIGNER
    edt-cli:
      auto-start: false
      version: "latest"
      interactive-mode: true
      working-directory: "R:\\Repos\\OpenIntegrations\\src\\ru\\BSL"
      startup-timeout-ms: 30000
      command-timeout-ms: 300000
      ready-check-timeout-ms: 5000
      
  platform-version: "8.3.26.1656"