# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v2
      - uses: otymko/setup-onescript@v1.4
        with:
          version: 1.3.0 # Требуемая версия OneScript

      - name: Выполнить скрипт
        run: oscript /.github/workflows/convert.os