# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  workflow_dispatch:

jobs:

  Decrypt:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Расшифровать тестовые данные
        run: gpg --quiet --batch --yes --decrypt --passphrase="$ENC_JSON" --output ./data.json ./data.json.gpg        
        env:
          ENC_JSON: ${{ secrets.ENC_JSON }}

  Convert:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      
    steps:

      - uses: actions/checkout@v2 
      - uses: otymko/setup-onescript@v1.4
        with:
          version: 1.3.0 # Требуемая версия OneScript

      - name: Выполнить скрипт преобразования OPI -> OInt
        run: oscript ./.github/workflows/convert.os
        
      - name: Установить asserts
        run: opm install asserts

      - name: Выполнить тесты
        run: |
          tree
          cd ..
          tree
          cd .. tree
          1testrunner -run ./OInt/tools/Modules/OPI_ПолучениеДанныхТестов.os 

      - name: Зашифровать данные обратно
        run: |
          rm -f ./data.json.gpg
          gpg --symmetric --cipher-algo AES256 --passphrase="$ENC_JSON"  data.json
        env:
          ENC_JSON: ${{ secrets.ENC_JSON }}

      - name: Check
        run: tree


      
