# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  workflow_dispatch:

jobs:


  Convert:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      
    steps:
    
      - uses: actions/checkout@v2 
      
      - name: Расшифровать тестовые данные
        run: gpg --quiet --batch --yes --decrypt --passphrase="$ENC_JSON" --output ./data.json ./data.json.gpg        
        env:
          ENC_JSON: ${{ secrets.ENC_JSON }}

      
      - uses: otymko/setup-onescript@v1.4
        with:
          version: 1.9.0 # Требуемая версия OneScript

      - name: Выполнить скрипт преобразования OPI -> OInt
        run: oscript ./.github/workflows/convert.os
        
      - name: Установить asserts и 1testrunner
        run: |
          opm install asserts
          opm install 1testrunner

      - name: Выполнить тесты
        run: oscript /home/runner/.local/share/ovm/current/lib/1testrunner/src/main.os -run ./OInt/tests/Modules/internal/OPI_Тесты.os

      - name: Зашифровать данные обратно
        run: |
          rm -f ./data.json.gpg
          gpg --symmetric --cipher-algo AES256 --passphrase="$ENC_JSON"  data.json
          rm -f ./data.json
        env:
          ENC_JSON: ${{ secrets.ENC_JSON }}

      - name: Проверка
        run: tree
      
      - uses: stefanzweifel/git-auto-commit-action@v5
       


      
