
name: Тестирование OINT CLI 

on:
  workflow_dispatch:

jobs:
  Decode:
    runs-on: ubuntu-latest
    steps:
    
      - uses: actions/checkout@v2 
      
      - name: Расшифровать тестовые данные
        run: gpg --quiet --batch --yes --decrypt --passphrase="$ENC_JSON" --output ./data.json ./data.json.gpg        
        env:
          ENC_JSON: ${{ secrets.ENC_JSON }}
      - name: Записать артефакт
        uses: actions/upload-artifact@v4
        with:
          name: test_data
          path: data.json

  Testing-Telegram:
    runs-on: ubuntu-latest
    needs: Decode
    steps:

    - name: Скачать артефакт с тестовой информацией
      uses: actions/download-artifact@v4
      with:
          name: test_data 
          
    - name: JSON to variables
      uses: rgarcia-phi/json-to-variables@v1.1.0
      with:
        filename: 'data.json'
        masked: true
      
    - name: Show output
      run: echo "${{ env.json_Twitter_Redirect }}"
