
name: Тестирование OINT CLI 

on:
  workflow_dispatch:

jobs:
  Decode:
    runs-on: ubuntu-latest
    steps:
    
      - uses: actions/checkout@v2 
      
      - name: Расшифровать тестовые данные
        run: gpg --quiet --batch --yes --decrypt --passphrase="$ENC_JSON" --output ./data.json ./data.json.gpg        
        env:
          ENC_JSON: ${{ secrets.ENC_JSON }}
          
      - name: Записать артефакт
        uses: actions/upload-artifact@v4
        with:
          name: test_data
          path: data.json

  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2             
      - uses: otymko/setup-onescript@v1.4
        with:
          version: 1.9.0 

      - name: Установить cmdline и asserts
        run: |
          opm install cmdline
          opm install asserts

      - name: Собрать и установить OInt
        run: |
          cd ./OInt
          opm build
          opm install oint-1.5.0.ospx  
          
      - name: Собрать бинарник
        run: |
          cd ./cli
          oscript -make app.os oint_bin

      - name: Записать артефакт
        uses: actions/upload-artifact@v4
        with:
          name: oint
          path: ./cli/oint_bin
        
  Testing-Telegram:
    runs-on: ubuntu-latest
    needs: [Decode, Build]
    steps:

    - name: Скачать артефакт с тестовой информацией
      uses: actions/download-artifact@v4
      with:
          name: test_data 
          
    - name: Скачать артефакт с исполняемым файлом
      uses: actions/download-artifact@v4
      with:
          name: oint 
          
    - name: JSON to variables
      uses: rgarcia-phi/json-to-variables@v1.1.0
      with:
        filename: 'data.json'
        masked: true
      
    - name: Выполнить Телеграм_ПолучитьИнформациюБота
      if: ${{ cancelled() }} == false
      run: oint_bin telegram ПолучитьИнформациюБота --token ${{ env.json_Telegram_Token }}
