name: Документация | Развернуть на Neocities (английская версия)

on:
  workflow_dispatch:

concurrency: 
  group: deploy-to-neocities
  cancel-in-progress: true

jobs:
  Deploy:
    runs-on: ubuntu-latest

    steps:
    
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - uses: otymko/setup-onescript@v1.4
      with:
        version: 1.9.0 

    - name: Перевести контент страниц
      run: oscript ./.github/workflows/os/docs_pagetranslate.os
        
    - uses: actions/setup-node@v4
      with:
        node-version: 18

    - name: Установка зависимостей
      run: |
        cd ./docs/docusaurus
        npm install
      
    - name: Сборка
      run: |
        cp -r ./docs/en/md ./docs/docusaurus/docs
        cd ./docs/docusaurus
        yarn build

    - name: Развертывание на neocities
      uses: bcomnes/deploy-to-neocities@v2
      with:
        api_token: ${{ secrets.NEOCITIES_API_TOKEN }}
        cleanup: true
        dist_dir: ./docs/docusaurus/build
