name: 1. MAIN | Основной процесс OPI -> OInt -> CLI

# Controls when the workflow will run
on: 
  [workflow_dispatch]
  
jobs:

  Convert:
    runs-on: ubuntu-latest
    permissions: 
      actions: write
      contents: write
     
    steps:
    
      - uses: actions/checkout@v2  
        with:
          token: ${{secrets.TOKEN}}   
                 
      - uses: otymko/setup-onescript@v1.4
        with:
          version: 1.9.0 

      - name: Установить зависимости
        run: |
          opm install cmdline
          opm install asserts
          opm install osparser
          opm install coloratos

      - name: Расшифровать тестовые данные
        run: gpg --quiet --batch --yes --decrypt --passphrase="$ENC_JSON" --output ./data.json ./data.json.gpg        
        env:
          ENC_JSON: ${{ secrets.ENC_JSON }}

      - name: Основной процесс преобразований
        run: oscript ./.github/workflows/os/main.os

      - name: Обновить Workflow тестирования CLI
        run: oscript ./.github/workflows/os/cli_testmaker.os

      - name: Обновить Workflow тестирования CLI (EN)
        run: oscript ./.github/workflows/os/cli_testmaker_en.os

      - uses: stefanzweifel/git-auto-commit-action@v5 
        with:
          commit_user_name: Vitaly the Alpaca (bot) 
          commit_user_email: vitaly.the.alpaca@gmail.com
          commit_author: Vitaly the Alpaca <vitaly.the.alpaca@gmail.com>
          commit_message: Преобразование OPI -> OInt (workflow)


