name: OINT | Определить покрытие

on:
  workflow_dispatch:

jobs:

  Convert:
    runs-on: ubuntu-latest
    permissions: 
      actions: write
      contents: write
     
    steps:
    
      - uses: actions/checkout@v2  
        with:
          token: ${{secrets.TOKEN}}   
                 
      - uses: otymko/setup-onescript@v1.4
        with:
          version: 1.9.0 
          
      - name: Установить 1commands, coverage и fs
        run: |
          opm install 1commands
          opm install coverage
          opm install fs

      - name: Установить OInt
        run: |
            cd ./src/ru/OInt
            opm build
            opm install *.ospx    

      - name: Выполнить скрипт определения покрытия
        run: oscript ./src/ru/OInt/coverage/Modules/Coverage_ОпределениеПокрытия.os



      - uses: stefanzweifel/git-auto-commit-action@v5 
        with:
          commit_user_name: Vitaly the Alpaca (bot) 
          commit_user_email: vitaly.the.alpaca@gmail.com
          commit_author: Vitaly the Alpaca <vitaly.the.alpaca@gmail.com>
          commit_message: Создание MD файлов документации